### ISSUE TITLE
trigger restore

### ISSUE THREAD

**Issue by ttlttc** [erickutcher/monitoroff#1]
I like this cute tool and it's very useful, thanks.

but I think it's have an advice, when i middle clicked and monitor turns black, if my mouse just moved a little, restore will be trigger, can you make it ignore mouse/keyboard input trigger for 2-5 seconds after turn black?

**Comment by erickutcher** [comment]
Unfortunately it's not possible as it's Windows that detects the movement and turns the monitor back on. I personally don't use the middle click option and instead press: Ctrl + Shift + F4

By using the keyboard command, you don't risk jiggling the mouse and accidentally turning it back on.

**Comment by ttlttc** [comment]
ok, thanks.
